[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cosmos-gradio"
version = "0.1.0"
description = "Gradio interface for Cosmos models"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    {name = "NVIDIA Corporation"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.10"
dependencies = [
    "gradio>=4.0.0",
    "torch>=1.12.0",
    "loguru>=0.6.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "black>=22.0",
    "flake8>=4.0",
    "flake8-pyproject>=1.0",
    "mypy>=0.950",
    "isort>=5.0",
]

[project.urls]
Homepage = "https://github.com/nvidia/cosmos-gradio"
Repository = "https://github.com/nvidia/cosmos-gradio"

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120
target-version = ["py310"]

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "W503"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
